Created Project structure. Initial LoadShop created
bsinkute/ElectronicShop pull request #2
Opened 2024-03-29 18:25 UTC by DAART15

task # 7

2024-03-29 18:41 UTC, bsinkute requested changes

2024-03-29 18:41 UTC, bsinkute commented on ElectronicShop/Models/Interfaces/ILoadShop.cs
> +        //cia metodas su tikslu >> pirmam pasirinkimui 1. Singup User 2. LogIn User 3. Login Admin 4. Exit
Mažytė klaida, bet vistiek vietoj `SingUp` turėtų būti `SignUp`

2024-03-29 18:41 UTC, bsinkute commented on ElectronicShop/Models/AdminLogIn.cs
> +
Nereikalingi tarpai

2024-03-29 18:41 UTC, bsinkute commented on ElectronicShop/Models/Interfaces/IAdmin.cs
> +
Nereikalingi tarpai

2024-03-29 18:41 UTC, bsinkute commented on ElectronicShop/Models/Interfaces/IUser.cs
> +
Nereikalingas tarpas

2024-03-29 18:41 UTC, bsinkute commented on ElectronicShop/Models/Interfaces/IUser.cs
> +
Nereikalingi tarpai

2024-03-29 18:41 UTC, bsinkute commented on ElectronicShop/Models/LoadShop.cs
> +        //1. SingUp User 2. LogIn User 3. Login Admin 4. Exit
`SignUp`

2024-03-29 18:41 UTC, bsinkute commented on ElectronicShop/Models/LoadShop.cs
> +
Nereikalingi tarpai

2024-03-29 18:41 UTC, bsinkute commented on ElectronicShop/Models/LoadShop.cs
> +        void ILoadShop.LoadShop(out int loadSelect)// sioje vietoje (out int loadSelect) kur daryti SWITCH
Nesu tikra, bet man atrodo, kad nereikia pilnai rašyti `void ILoadShop.LoadShop` užtenka be interface pavadinimo `void LoadShop`

2024-03-29 18:41 UTC, bsinkute commented on ElectronicShop/Models/LoadShop.cs
> +                bool isLoadCorect= int.TryParse(Console.ReadLine(),out  loadSelect);
Tarpo nėra prieš lygybės ženklą ir po kablelio prieš `out`

2024-03-29 18:41 UTC, bsinkute commented on ElectronicShop/Models/LoadShop.cs
> +                Console.WriteLine("1. SingUp User \n2. LogIn User \n3. Login Admin \n4. Exit");
`SignUp`

2024-03-29 18:41 UTC, bsinkute commented on ElectronicShop/Models/LoadShop.cs
> +                else if (isLoadCorect && loadSelect == 4) break;
Galbūt prieš išėjimą būtų gerai išvesti naudotojui žinutę, kad jis išeina?

2024-03-29 18:41 UTC, bsinkute commented on ElectronicShop/Models/UserLogIn.cs
> +
Nereikalingos eilutės

2024-03-29 18:41 UTC, bsinkute commented on ElectronicShop/Models/UserSingUp.cs
> +﻿
Nereikalinga eilutė

2024-03-29 18:41 UTC, bsinkute commented on ElectronicShop/Program.cs
> +
nereikalingas tarpas

2024-03-29 18:48 UTC, DAART15 commented on ElectronicShop/Models/Interfaces/ILoadShop.cs
> +        //cia metodas su tikslu >> pirmam pasirinkimui 1. Singup User 2. LogIn User 3. Login Admin 4. Exit
patvarkysiu kai kartu su kitu pull reqest darysiu

2024-03-29 18:49 UTC, DAART15 commented on ElectronicShop/Models/LoadShop.cs
> +                else if (isLoadCorect && loadSelect == 4) break;
ok, dadėsiu  informaciją

2024-03-29 19:01 UTC, bsinkute commented on ElectronicShop/Models/Interfaces/ILoadShop.cs
> +        //cia metodas su tikslu >> pirmam pasirinkimui 1. Singup User 2. LogIn User 3. Login Admin 4. Exit
Jeigu kažkas pradės daryti ant šitos klasės, tai bus poto konfliktai, tai geriau sutvarkyti su šituo pull requestu.

2024-04-02 16:04 UTC, bsinkute approved these changes

2024-04-02 16:15 UTC, merged